#include "application.h"
#include "codetacc-wearables/Adafruit_Sensor.h"
#include "codetacc-wearables/Adafruit_LSM9DS0.h"
#include "codetacc-wearables/Adafruit_SI1145.h"
#include "codetacc-wearables/Adafruit_TCS34725.h"
#include "codetacc-wearables/Adafruit_TSL2561_U.h"
